### ISSUE TITLE
curious about which llama checkpoint 

### ISSUE THREAD

**Issue by Dali936** [ziqipang/LM4VisualEncoding#10]
thanks for your excellent work !
![image](https://github.com/user-attachments/assets/338f0b95-3cee-4943-a853-9cea5755e105)
here the checkpoint above. which checkpoint should i choose

**Comment by ziqipang** [comment]
@944104439 I was using LLaMA-1 7B at the time

**Comment by Dali936** [comment]
> @944104439 I was using LLaMA-1 7B at the time

thanks for your clear reply !
