### ISSUE TITLE
About importing pre-trained weights for the LLaMA model

### ISSUE THREAD

**Issue by Changwei-Ouyang** [ziqipang/LM4VisualEncoding#3]
1. In the code for action recognition, I'm a bit confused about the part where pre-trained weights for the LLaMA model are imported. Can you please point out the section of code that handles the import of pre-trained weights for the LLaMA model?
2. Can you provide the pre-trained weights for the LLaMA model you are using?

**Comment by ziqipang** [comment]
@Changwei-Ouyang Thanks for the question!
- This [line](https://github.com/ziqipang/LM4VisualEncoding/blob/38acd21f31b2e0226815b51db9cc56c54db237fb/video_understanding/run_class_finetuning.py#L335) loads the weights of LLaMA. I wrote a function in `llama.py` that supports loading one layer of transformer at [here](https://github.com/ziqipang/LM4VisualEncoding/blob/38acd21f31b2e0226815b51db9cc56c54db237fb/video_understanding/llama.py#L253).
- Sorry about it that I am not sure if I am allowed to distribute the weights of LLaMA publicly. But I just made some updates to the doc of action recognition explaining the preparation of LLaMA. Hope this helps!

**Comment by Changwei-Ouyang** [comment]
Thank you for your response, very interesting work! Now I understand.
