### ISSUE TITLE
Some questions about ViT-Small-LLaMA

### ISSUE THREAD

**Issue by 1090h2400** [ziqipang/LM4VisualEncoding#4]
Hi sir！ Thanks for your great work. I would like to know if the checkpoint about ViT-Small-LLaMA includes the LLaMA model.

**Comment by ziqipang** [comment]
It includes the LLaMA layer we used (the 32nd of LLaMA), corresponding to [`self.llama`](https://github.com/ziqipang/LM4VisualEncoding/blob/b3aa78ef9f75e81ebc395e6915206578f1f2cbce/image_classification/models/vit_llama.py#L94) in the `state_dict`.
