### ISSUE TITLE
LLMBoostMedical

### ISSUE THREAD

**Issue by daydayupzzl** [ziqipang/LM4VisualEncoding#9]
https://github.com/ZhixinLai/LLMBoostMedical what is the difference

**Comment by ziqipang** [comment]
@daydayupzzl  Cannot open?

**Comment by daydayupzzl** [comment]
very sorry, previous gitHub repository may have been closed now, you can refer to this link https://arxiv.org/pdf/2403.17343.pdf to view more information about it. 
 @misc{lai2024language,
    title={Language Models are Free Boosters for Biomedical Imaging Tasks},
    author={Zhixin Lai and Jing Wu and Suiyao Chen and Yucheng Zhou and Naira Hovakimyan},
    year={2024},
    eprint={2403.17343},
    archivePrefix={arXiv},
    primaryClass={cs.CV}
}

**Comment by ziqipang** [comment]
@daydayupzzl Thanks for letting me know! This seems a follow-up of our work. What kind of information are you interested in?

**Comment by daydayupzzl** [comment]
thank you for your reply, just curious about the two articles. thanks again!
